liquibase:
    context: production, test
    
spring:
    datasource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        url: ${DB_HOSTNAME}
        port: 5432
        databaseName: pidas_public_tenance
        poolName: SpringBootHikariCP
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        testWhileIdle: true
        validationQuery: SELECT 1
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL94Dialect
        openInView: false
        show_sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            use-new-id-generator-mappings: true
        properties:
            hibernate.cache.use_second_levelt_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.hbm2ddl.auto: validate

logging:
   level: 
      org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: WARN