spring:
    datasource:
        url: jdbc:mysql://localhost:3306/db_todoapp?useSSL=false
        username: root
        password: admin
        data: classpath:data.sql
        initialization-mode: never
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8081
  servlet:
    context-path: /api